(asdf:defsystem #:rougespace
  :depends-on (#:tcod)
  :components ((:file "util")
	       (:file "rougespace")
	       (:file "drawable")
	       (:file "thing")
	       (:file "camera")
	       (:file "world")
	       (:file "generator")
	       (:file "renderer")
	       (:file "object")
	       (:file "player")))
